insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('ABY', 'SH', 'Abyssinian', 'абиссинская');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('ACL', 'SLH', 'American Curl', 'американский керл (ПДШ)');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('ACR', 'SH', 'American Curl', 'американский керл (КШ)');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('ASH', 'SH', 'American Shorthair', 'американская короткошерстная');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('AWH', 'SH', 'American Wirehair', 'американская жесткошерстная');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('BAL', 'SLH', 'Balinese', 'балинезийская');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('BEN', 'SH', 'Bengal', 'бенгальская');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('BMI', 'SH', 'Burmilla', 'бурмилла');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('BOM', 'SH', 'Bombay', 'бомбейская');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('BRI', 'SH', 'British Shorthair', 'британская короткошерстная');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('BRL', 'SLH', 'British longhair', 'британская длинношерстная');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('BUR', 'SH', 'Burmese', 'бурманская (бурма)');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('CHA', 'SH', 'Chartreux', 'картезианская (шартрез)');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('CRX', 'SH', 'Cornish Rex', 'корниш-рекс');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('DRX', 'SH', 'Devon Rex', 'девон-рекс');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('DSX', 'SH', 'Don Sphinx', 'донской сфинкс');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('EXO', 'LH', 'Exotic', 'экзотическая короткошерстная');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('GRX', 'SH', 'German Rex', 'германский рекс');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('JBT', 'SH', 'Japanese Bobtail', 'японский бобтейл (КШ)');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('JBT', 'SLH', 'Japanese Bobtail', 'японский бобтейл');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('KAB', 'SH', 'Karelian Bobtail', 'карельский бобтейл (КШ)');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('KAB', 'SLH', 'Karelian Bobtail', 'карельский бобтейл (ПДШ)');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('KBL', 'SLH', 'Kurilian Bobtail', 'курильский бобтейл (ПДШ)');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('KBS', 'SH', 'Kurilian Bobtail', 'курильский бобтейл (КШ)');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('KOR', 'SH', 'Korat', 'корат');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('LPM', 'SLH', 'La Perm', 'лаперм');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('MAN', 'SH', 'Manx', 'мэнкс (мэнская бесхвостая кошка)');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('MAU', 'SH', 'Egyptian Mau', 'египетскаямау');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('MBT', 'SOSH', 'Mekong-Bobtail', 'меконгский бобтейл');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('MCO', 'SLH', 'Maine Coon', 'мейн-кун');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('MNL', 'SLH', 'Manchkin longhair', 'манчкин (ДШ)');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('MNS', 'SH', 'Manchkin Shorthair', 'манчкин (КШ)');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('NEB', 'SLH', 'Nebelung', 'нибелунг');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('NEV', 'SLH', 'Neva Masquerade', 'невская маскарадная');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('NFO', 'SLH', 'Norwegian Forest Cat', 'норвежская лесная');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('OCI', 'SH', 'Ocicat', 'оцикэт');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('OKH', 'SOSH', 'Oriental Shorthair ORI, OSH,', 'ориентальная короткошерстная');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('PBD', 'SOSH', 'Peterbald', 'петерболд');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('PER', 'LH', 'Persian', 'персидская');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('RAG', 'SLH', 'Ragdoll', 'рэгдолл');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('RUS', 'SH', 'Russian Blue', 'русская голубая');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('SBI', 'SLH', 'Sacred birman', 'бирманская (священная бирма)');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('SFL*', 'SLH', 'Scottish fold longhair (Highland Fold)', 'хайленд-фолд');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('SFS', 'SH', 'Scottish Fold Shorthair', 'шотландская вислоухая (скоттиш-фолд)');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('SFS 71', 'SH', 'Scottish Straight Shorthair', 'шотландская короткошерстная (скоттиш-страйт)');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('SIA', 'SOSH', 'Siamese', 'сиамская');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('SIB', 'SLH', 'Siberian Cat', 'сибирская');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('SIN', 'SH', 'Singapura', 'сингапура');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('SNO', 'SLH', 'Snowshoe', 'сноу-шу');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('SOM', 'SLH', 'Somali', 'сомали');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('SPH', 'SH', 'Canadian Sphynx', 'канадский сфинкс');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('SRX', 'SH', 'Selkirk Rex Shorthair', 'селкирк-рекс (КШ)');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('SRX', 'SLH', 'Selkirk Rex', 'селкирк-рекс (ПДШ)');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('THA', 'SOSH', 'Thai', 'тайская');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('TON', 'SOSH', 'Tonkinese', 'тонкинская (тонкинез)');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('TUA', 'SLH', 'Turkish Angora', 'турецкая ангора');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('TUV', 'SLH', 'Turkish Van', 'турецкий ван');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('URX', 'SH', 'Ural Rex', 'уральский рекс (КШ)');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('URX', 'SLH', 'Ural Rex', 'уральский рекс (ПДШ)');
insert into Breeds (IdBreed, IdGroup, NameEng, NameNat) values ('YOR', 'SLH', 'York', 'йорк');
